# supabase/config.toml

project_id = "lauydzfbtlsocfsljpcn"

[api]
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54324

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:8080"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

# This section applies to the 'invite-user' function
[functions.invite-user]
verify_jwt = true